// AUTH
export const AUTH_REQUEST = "AUTH_REQUEST ";
export const AUTH_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAIL = "AUTH_REQUEST_FAIL";
export const AUTH_REGISTRATION_REQUEST = "AUTH_REGISTRATION_REQUEST";
// LOGIN
export const AUTH_LOGIN = "AUTH_LOGIN";
// LOGOUT
export const LOGOUT = "LOGOUT";
